esphome:
  name: esphome-web-b1d4e7
  friendly_name: esp_Oven

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key here"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    name: "Oven Preheated"
    pin:
      number: D1
      inverted: true
      mode:
        input: true
        pullup: false   